stages:
  - lint
  - build
  - test

frontend-lint:
  stage: lint
  image: node:20.11.1
  before_script:
    - cd src/frontend
    - npm install
    - npm install -g eslint
    - npm install -g eslint-config-next
  script:
    - npm run lint
  only:
    - prod/frontend

webserver-lint:
  stage: lint
  image: python:3.11
  before_script:
    - cd src/python_web_api
    - pip install -r requirements.txt
    - pip install mypy
  script:
    - mypy --ignore-missing-imports --disable-error-code=import-untyped --exclude setup.py --exclude build/* .
  only:
    - prod/webserver

frontend-build:
  stage: build
  image: node:20.11.1
  before_script:
    - cd src/frontend
    - npm install
  script:
    - npm run build
  only:
    - prod/frontend

webserver-build:
  stage: build
  image: python:3.11
  before_script:
    - cd src/python_web_api
    - pip install -r requirements.txt
  script:
    - pip install src/
  only:
    - prod/webserver

proxyserver-build:
  stage: build
  image: gradle:jdk-17
  before_script:
    - cd src/java-socket-server
  script:
    - ./gradlew build
  only:
    - prod/proxyserver

frontend-test:
  stage: test
  image: node:20.11.1
  before_script:
    - cd src/frontend
    - npm install
  script:
    - npm test
  only:
    - prod/frontend

webserver-test:
  stage: test
  image: python:3.11
  before_script:
    - cd src/python_web_api
    - pip install -r requirements.txt
    - pip install src/
    # Setup a Mock Echo Server for client/server tests
    - python3 -m tests.client.echo_server 46900 46901 46903 46905 > /dev/null &
  script:
    - coverage run --omit=tests/*,setup.py,__init__.py "--source=app,views.mock,webserver" tests/__init__.py
  after_script:
    - cd src/python_web_api
    - coverage report
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: src/python_web_api/coverage.xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  only:
    - prod/webserver

proxyserver-test:
  stage: test
  image: gradle:jdk-17
  before_script:
    - cd src/java-socket-server
    - ./gradlew build
  script:
    - ./gradlew test
  only:
    - prod/proxyserver

frontend-webserver-test:
  stage: test
  image: docker:26.0.0
  services:
    - docker:26.0.0-dind
  tags:
    - dind
  before_script:
    - docker ps
    - docker compose up -d --build frontend web_server
  script:
    - docker exec frontend bash -c "npm test"
  after_script:
    - docker compose down
  only:
    - main

webserver-proxyserver-test:
  stage: test
  image: docker:26.0.0
  services:
    - docker:26.0.0-dind
  tags:
    - dind
  before_script:
    - docker ps
    - docker compose up -d --build web_server proxy_server
  script:
    - docker exec web_server bash -c "python3 -m tests.integration.integration_test"
  after_script:
    - docker compose down
  only:
    - main
